In [6]:
import pandas as pd

In [7]:
# Declarar as variaveis para acessar o arquivo

path = 'C:\\Users\\FIC\\Documents\\Fabiana Python\\003 - Arquivos\\'
file = 'dados-vendas.xlsx'

# Acessar os dados do arquivo e colocar em um dataframe

dados = pd.read_excel(path + file, sheet_name='Vendas')

In [8]:
dados.head()

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Data Venda,ValorVenda
0,SKU-0000001,LG K10 TV Power,Celulares,Corporativo,LG,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,2012-10-04,679.00
1,SKU-0000002,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,2012-01-01,832.00
2,SKU-0000003,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,2012-02-02,790.00
3,SKU-0000004,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,2012-03-03,765.32
4,SKU-0000005,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Artur Moreira,1004,2012-04-04,459.89

In [9]:
#Seleciona apenas a coluna Vendedor e remove as duplicadas
df_cidade = dados['Cidade'].drop_duplicates()

# Converter o Pandas Series em uma lista
lista_cidade = df_cidade.tolist()

lista_cidade

['São Paulo',
 'Belo Horizonte',
 'Rio de Janeiro',
 'Vitória',
 'Cascavel',
 'Salvador',
 'Osasco',
 'Campinas',
 'Campos',
 'Petrópolis']

In [10]:
# Estrutura para gerar os aruivos de forma automatica

#for vendedores in lista_vendedores:

dados[dados['Cidade']== 'Osasco']

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Data Venda,ValorVenda
170,SKU-0000171,Samsung Galaxy 8,Celulares,Corporativo,Samsung,S6543,Osasco,São Paulo,André Pereira,1002,2015-03-02,3999.0
171,SKU-0000172,Samsung Galaxy 8,Celulares,Corporativo,Samsung,S6543,Osasco,São Paulo,André Pereira,1002,2015-04-02,3999.0
172,SKU-0000173,Samsung Galaxy 8,Celulares,Corporativo,Samsung,S6543,Osasco,São Paulo,Artur Moreira,1004,2015-05-02,3999.0
280,SKU-0000281,Ventilador,Eletroportáteis,Doméstico,Arno,S6543,Osasco,São Paulo,Artur Moreira,1004,2015-05-02,189.0
282,SKU-0000283,Ventilador,Eletroportáteis,Doméstico,Arno,S6543,Osasco,São Paulo,Maria Fernandes,1001,2015-07-02,156.0
283,SKU-0000284,Ventilador,Eletroportáteis,Doméstico,Arno,S6543,Osasco,São Paulo,Maria Fernandes,1001,2015-08-02,123.0
284,SKU-0000285,Ventilador,Eletroportáteis,Doméstico,Arno,S6543,Osasco,São Paulo,Maria Fernandes,1001,2015-09-02,156.0

In [11]:
# Estrutura para gerar os aruivos de forma automatica

for cidade in lista_cidade:
    df_final = dados[dados['Cidade']== cidade]
    path_New = path + 'relatorio-venda cidade\\'
    # Salvar o arquivo na pasta
    df_final.to_excel(path_New + cidade + '.xlsx',index = False)