In [22]:
import pandas as pd

In [23]:
# nba - a

path = 'C:\\Users\\FIC\\Documents\\Fabiana Python\\003 - Arquivos\\nba\\'
file = 'nba_2015_a.csv'

#Alocar o documento em um Datafreme

df_a = pd.read_csv(path + file)

# Visualizar o cabeçalho dos dados

df_a.head()

,Player,Position,ID,Draft Year,Projected SPM,Superstar,Starter,Role Player
0,Karl-Anthony Towns,C,karl-anthony-towns,2015,1.030606,0.134767,0.427183,0.163083
1,Justise Winslow,SF,justise-winslow,2015,0.875329,0.083529,0.510905,0.176767
2,Stanley Johnson,SF,stanley-johnson,2015,0.679493,0.067800,0.423733,0.278500
3,Jahlil Okafor,C,jahlil-okafor,2015,0.521661,0.058717,0.409900,0.235533
4,D`Angelo Russell,PG,d-angelo-russell,2015,0.511967,0.152033,0.342283,0.096583

In [24]:
# nba - b

path = 'C:\\Users\\FIC\\Documents\\Fabiana Python\\003 - Arquivos\\nba\\'
file = 'nba_2015_b.csv'

#Alocar o documento em um Datafreme

df_b = pd.read_csv(path + file)

# Visualizar o cabeçalho dos dados

df_b.head()

,Player,Position,ID,Draft Year,Projected SPM,Superstar,Starter,Role Player
0,Austin Rivers,SG,austin-rivers,2012,-0.145824,0.036233,0.268867,0.334098
1,Royce White,SF,royce-white,2012,-0.193490,0.018400,0.243750,0.357367
2,Damian Lillard,PG,damian-lillard,2012,-0.200562,0.036314,0.259300,0.273522
3,Tony Wroten,PG,tony-wroten,2012,-0.245215,0.021567,0.280567,0.286900
4,Doron Lamb,SG,doron-lamb,2012,-0.281442,0.004280,0.208319,0.439637

In [25]:
# nba - c

path = 'C:\\Users\\FIC\\Documents\\Fabiana Python\\003 - Arquivos\\nba\\'
file = 'nba_2015_c.csv'

#Alocar o documento em um Datafreme

df_c = pd.read_csv(path + file)

# Visualizar o cabeçalho dos dados

df_c.head()

,Player,Position,ID,Draft Year,Projected SPM,Superstar,Starter,Role Player
0,Mustafa Shakur,PG,mustafa-shakur,2007,-1.304224,0.000728,0.027577,0.328555
1,Jermareo Davidson,PF,jermareo-davidson,2007,-1.305091,0.000098,0.028128,0.348323
2,Ekene Ibekwe,PF,ekene-ibekwe,2007,-1.313002,0.000349,0.018529,0.334192
3,Cartier Martin,SF,cartier-martin,2007,-1.315787,0.000206,0.017471,0.363321
4,Ivan Radenovic,PF,ivan-radenovic,2007,-1.327384,0.000090,0.026357,0.341746

In [26]:
# nba - d

path = 'C:\\Users\\FIC\\Documents\\Fabiana Python\\003 - Arquivos\\nba\\'
file = 'nba_2015_d.csv'

#Alocar o documento em um Datafreme

df_d = pd.read_csv(path + file)

# Visualizar o cabeçalho dos dados

df_d.head()

,Player,Position,ID,Draft Year,Projected SPM,Superstar,Starter,Role Player
0,Samardo Samuels,PF,samardo-samuels,2010.0,-1.097613,0.001910,0.067415,0.355177
1,Larry Sanders,PF,larry-sanders,2010.0,-1.099703,0.001010,0.067939,0.356190
2,Jeremy Evans,SF,jeremy-evans,2010.0,-1.111429,0.000000,0.050159,0.397297
3,Stanley Robinson,SF,stanley-robinson,2010.0,-1.116975,0.000145,0.061203,0.385924
4,Jerome Randle,PG,jerome-randle,2010.0,-1.146297,0.000000,0.044072,0.384182

In [30]:
# bust

path = 'C:\\Users\\FIC\\Documents\\Fabiana Python\\003 - Arquivos\\nba\\'
file = 'bust_nba_2015.csv'

#Alocar o documento em um Datafreme

df_bust = pd.read_csv(path + file)

# Visualizar o cabeçalho dos dados

df_bust.head()

                   ID      Bust
0  karl-anthony-towns  0.274967
1     justise-winslow  0.228800
2     stanley-johnson  0.229967
3       jahlil-okafor  0.295850
4    d-angelo-russell  0.409100

#### c) Concatene os arquivos df_a, df_b e df_c, usando a função concat() usando os índices. Salve um dataframe chamado df_total.

In [28]:
df_total = pd.concat([df_a, df_b,df_c],ignore_index=True)

df_total

,Player,Position,ID,Draft Year,Projected SPM,Superstar,Starter,Role Player
0,Karl-Anthony Towns,C,karl-anthony-towns,2015,1.030606,0.134767,0.427183,0.163083
1,Justise Winslow,SF,justise-winslow,2015,0.875329,0.083529,0.510905,0.176767
2,Stanley Johnson,SF,stanley-johnson,2015,0.679493,0.067800,0.423733,0.278500
3,Jahlil Okafor,C,jahlil-okafor,2015,0.521661,0.058717,0.409900,0.235533
4,D`Angelo Russell,PG,d-angelo-russell,2015,0.511967,0.152033,0.342283,0.096583
...,...,...,...,...,...,...,...,...
1083,Terrell Lyday,SG,terrell-lyday,2001,-1.486319,0.001152,0.018303,0.261035
1084,Brandon Wolfram,SF,brandon-wolfram,2001,-1.493460,0.000271,0.011532,0.271560
1085,Ruben Boumtje Boumtje,C,ruben-boumtje-boumtje,2001,-1.494069,0.000000,0.020653,0.236919
1086,Greg Stevenson,SG,greg-stevenson,2001,-1.529188,0.000000,0.019693,0.238861
1087,Calvin Bowman,C,calvin-bowman,2001,-1.684669,0.000000,0.005068,0.168629

#### d) Faça a concatenação do dataframe df_total com o dataframe bust, utilizando a função merge() e a variável ID.

In [31]:
df_total = pd.merge(df_total,df_bust,on='ID',how='left')

df_total

,Player,Position,ID,Draft Year,Projected SPM,Superstar,Starter,Role Player,Bust
0,Karl-Anthony Towns,C,karl-anthony-towns,2015,1.030606,0.134767,0.427183,0.163083,0.274967
1,Justise Winslow,SF,justise-winslow,2015,0.875329,0.083529,0.510905,0.176767,0.228800
2,Stanley Johnson,SF,stanley-johnson,2015,0.679493,0.067800,0.423733,0.278500,0.229967
3,Jahlil Okafor,C,jahlil-okafor,2015,0.521661,0.058717,0.409900,0.235533,0.295850
4,D`Angelo Russell,PG,d-angelo-russell,2015,0.511967,0.152033,0.342283,0.096583,0.409100
...,...,...,...,...,...,...,...,...,...
1083,Terrell Lyday,SG,terrell-lyday,2001,-1.486319,0.001152,0.018303,0.261035,0.719510
1084,Brandon Wolfram,SF,brandon-wolfram,2001,-1.493460,0.000271,0.011532,0.271560,0.716636
1085,Ruben Boumtje Boumtje,C,ruben-boumtje-boumtje,2001,-1.494069,0.000000,0.020653,0.236919,0.742427
1086,Greg Stevenson,SG,greg-stevenson,2001,-1.529188,0.000000,0.019693,0.238861,0.741446
1087,Calvin Bowman,C,calvin-bowman,2001,-1.684669,0.000000,0.005068,0.168629,0.826303