In [1]:
import pandas as pd

In [2]:
# Declarar as variaveis para acessar o arquivo

path = 'C:\\Users\\FIC\\Documents\\Fabiana Python\\003 - Arquivos\\'
file = 'dados-vendas.xlsx'

# Acessar os dados do arquivo e colocar em um dataframe

dados = pd.read_excel(path + file, sheet_name='Vendas')

In [3]:
dados.head()

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Data Venda,ValorVenda
0,SKU-0000001,LG K10 TV Power,Celulares,Corporativo,LG,SP8821,São Paulo,São Paulo,Ana Teixeira,1009,2012-10-04,679.00
1,SKU-0000002,Geladeira Duplex,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,2012-01-01,832.00
2,SKU-0000003,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Josias Silva,1006,2012-02-02,790.00
3,SKU-0000004,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Brastemp,SP8821,São Paulo,São Paulo,Mateus Gonçalves,1003,2012-03-03,765.32
4,SKU-0000005,Lavadora 11 Kg,Eletrodomésticos,Doméstico,Electrolux,SP8821,São Paulo,São Paulo,Artur Moreira,1004,2012-04-04,459.89

In [4]:
#Seleciona apenas a coluna Vendedor e remove as duplicadas
df_estado = dados['Estado'].drop_duplicates()

# Converter o Pandas Series em uma lista
lista_estado = df_estado.tolist()

lista_estado

['São Paulo',
 'Minas Gerais',
 'Rio de Janeiro',
 'Espírito Santo',
 'Paraná',
 'Bahia']

In [5]:
dados[dados['Estado']== 'Paraná']

,ID-Produto,Produto,Categoria,Segmento,Fabricante,Loja,Cidade,Estado,Vendedor,ID-Vendedor,Data Venda,ValorVenda
87,SKU-0000088,Fritadeira,Eletroportáteis,Doméstico,Arno,P0761,Cascavel,Paraná,Artur Moreira,1004,2013-01-02,297.0
89,SKU-0000090,Aspirador,Eletroportáteis,Doméstico,Britânia,P0761,Cascavel,Paraná,Josias Silva,1006,2013-03-02,167.0
128,SKU-0000129,Secadora Vapor,Eletrodomésticos,Doméstico,Brastemp,P0761,Cascavel,Paraná,Josias Silva,1006,2013-06-02,799.9
240,SKU-0000241,Micro-Ondas,Eletrodomésticos,Doméstico,Consul,P0761,Cascavel,Paraná,Josias Silva,1006,2015-01-02,290.0
242,SKU-0000243,Ar Condicionado,Eletrodomésticos,Industrial,Samsung,P0761,Cascavel,Paraná,Mateus Gonçalves,1003,2015-03-02,455.0
278,SKU-0000279,Ventilador,Eletroportáteis,Doméstico,Arno,P0761,Cascavel,Paraná,Artur Moreira,1004,2015-03-02,123.0
281,SKU-0000282,Ventilador,Eletroportáteis,Doméstico,Arno,P0761,Cascavel,Paraná,Rodrigo Fagundes,1005,2015-06-02,134.0

In [7]:
# Estrutura para gerar os aruivos de forma automatica

for estado in lista_estado:
    df_final = dados[dados['Estado']== estado]
    path_New = path + 'relatorio-venda estado\\'
    # Salvar o arquivo na pasta
    df_final.to_excel(path_New + estado + '.xlsx',index = False)